"""add deleted_at field

Revision ID: 0831d0428f69
Revises: 091a10492adb
Create Date: 2018-07-30 19:12:34.003357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0831d0428f69'
down_revision = '091a10492adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embed', sa.Column('delete_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embed', 'delete_at')
    # ### end Alembic commands ###
